#63
Project-Stage-Academy/UA1244_alpha pull request #72
Opened 2024-10-09 12:57 UTC by 0leksandrr

**Implemented Models for Investors**

- Created models for investors with the necessary attributes.

**Note:**
I am currently unsure if a custom manager is required for these models at this moment, as it can be created if necessary in the future.

2024-10-09 16:57 UTC, PolinaCh14 approved these changes

2024-10-10 14:00 UTC, 0leksandrr commented on investors/models.py
> +    investor_logo = models.ImageField(upload_to='investor_logos/', blank=True)
Done

2024-10-10 14:00 UTC, 0leksandrr commented on investors/models.py
> +    updated_at = models.DateTimeField(auto_now=True)
Done

2024-10-10 14:00 UTC, 0leksandrr commented on startups/serializers.py
Done

2024-10-10 14:00 UTC, 0leksandrr commented on startups/tests.py
Done

2024-10-10 14:34 UTC, mehalyna requested changes

2024-10-10 16:49 UTC, 0leksandrr commented on startups/views.py
done

2024-10-10 16:49 UTC, 0leksandrr commented on investors/models.py
> +    updated_at = models.DateTimeField(auto_now=True)
done

2024-10-10 16:57 UTC, VIad0s approved these changes

2024-10-11 14:21 UTC, mehalyna requested changes

2024-10-11 14:21 UTC, mehalyna commented on startups/serializers.py
![image](https://github.com/user-attachments/assets/66d31100-ce43-4a90-878b-c9a99f5113c5)

2024-10-11 14:21 UTC, mehalyna commented on startups/tests.py
![image](https://github.com/user-attachments/assets/ae5e9351-a1d0-4fb2-85f2-6ad50dc65294)

2024-10-11 16:40 UTC, 0leksandrr commented on startups/serializers.py
done

2024-10-11 16:40 UTC, 0leksandrr commented on startups/tests.py
done

2024-10-13 11:38 UTC, mehalyna approved these changes

2024-10-13 14:45 UTC, merged