#46
Project-Stage-Academy/UA1244_alpha pull request #78
Opened 2024-10-13 14:35 UTC by DMan113

Everything works, but there are doubts about the choice of serializer.

2024-10-14 12:36 UTC, mehalyna requested changes

2024-10-14 12:36 UTC, mehalyna commented on users/serializers.py
> +#         read_only_fields = ('is_active',)
You might want to uncomment the `UserSerializer` section if you need a simple read-only representation of users in another part of your application (without the password field).

2024-10-14 12:36 UTC, mehalyna commented on users/serializers.py
> +        return user
When creating or updating a user with multiple related objects (like roles), it's safer to use a transaction to ensure all operations succeed or are rolled back if one fails. This prevents cases where the user might be created without proper role assignments due to an error.
```
from django.db import transaction

def create(self, validated_data):
    roles_data = validated_data.pop('roles', [])
    with transaction.atomic():
        user = User.objects.create(**validated_data)
        user.set_password(validated_data['password'])
        user.save()
        if roles_data:
            user.roles.set(roles_data)
    return user
```

2024-10-14 12:36 UTC, mehalyna commented on users/serializers.py
**DRY** You are repeating the same logic for role assignments and password handling in both `create` and `update` methods. This logic can be refactored into helper methods to make the code cleaner and more maintainable.
```
def set_roles_and_password(self, instance, validated_data):
    if 'password' in validated_data:
        instance.set_password(validated_data['password'])
    if 'roles' in validated_data:
        instance.roles.set(validated_data['roles'])

def create(self, validated_data):
    user = User.objects.create(**validated_data)
    self.set_roles_and_password(user, validated_data)
    user.save()
    return user

def update(self, instance, validated_data):
    self.set_roles_and_password(instance, validated_data)
    instance.save()
    return instance
```

2024-10-14 12:36 UTC, mehalyna commented on users/serializers.py
If you want to enforce a specific image type or size limit for the profile picture, you could add validation for the `profile_picture` field. This can help prevent users from uploading invalid files.
```
def validate_profile_picture(self, value):
    if value and value.size > 5 * 1024 * 1024:  # 5MB max size
        raise serializers.ValidationError("Profile picture is too large.")
    return value
```

2024-10-14 12:36 UTC, mehalyna commented on users/views.py
Instead of manually checking credentials and returning tokens, use the built-in `TokenObtainPairSerializer` for better handling of token generation and credential checking
```
from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework_simplejwt.views import TokenObtainPairView
from rest_framework.response import Response
from rest_framework import status

class CustomTokenObtainPairView(TokenObtainPairView):
    def post(self, request, *args, **kwargs):
        serializer = TokenObtainPairSerializer(data=request.data)
        try:
            serializer.is_valid(raise_exception=True)
            user = serializer.user
            refresh = serializer.validated_data['refresh']
            access = serializer.validated_data['access']
            
            return Response({
                'refresh': str(refresh),
                'access': str(access),
                'user_id': user.id,
                'email': user.email,
            }, status=status.HTTP_200_OK)
        except Exception as e:
            return Response({'error': 'Invalid credentials.'}, status=status.HTTP_401_UNAUTHORIZED)
```

2024-10-17 02:56 UTC, mehalyna approved these changes

2024-10-17 10:35 UTC, VIad0s approved these changes

2024-10-17 15:14 UTC, merged